### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by tazjin** [UWIT-IAM/nginx-saml-proxy#8]
Thanks for this project; I was wondering if you were planning to release it under / add an open-source license?

**Comment by tomthorogood** [comment]
@tazjin Thanks so much for the request. We've taken care of this and added the Apache 2.0 license in https://github.com/UWIT-IAM/nginx-saml-proxy/commit/b59e2ddc8de017b3c968bb480605f3f61eb944f6

Cheers!

**Comment by tazjin** [comment]
Thank you! :)
